### ISSUE TITLE
Override themeData

### ISSUE THREAD

**Issue by jim012** [andyduke/filesystem_picker#16]
Hello, I'd like to customize the theme of the picker but it only accepts the main themeData.
Wrapping the calling widget into a Theme() widget is not working.
What solution can be used to independently from the main theme change the styles?

Here an example:
```
Widget build(BuildContext context) {
    return Theme(
      data: ThemeData(scaffoldBackgroundColor: Colors.black),
      child: FloatingActionButton(
        backgroundColor: backgroundDarkColor,
        onPressed: () async {
          Directory appDocDir = gitPath.folder != null
              ? Directory(gitPath.folder)
              : Directory('C:/');
          String path = await FilesystemPicker.open(
            title: 'Git Folder',
            context: context,
            rootDirectory: appDocDir,
            fsType: FilesystemType.folder,
            pickText: 'Pick this folder',
            folderIconColor: Colors.white,
          );
          gitPath.setPath(path);
        },
        child: Icon(
          Icons.folder_open,
        ),
      ),
    );
  }
```
I expect the background of the picker to be black.

**Comment by andyduke** [comment]
@jim012 Wrapping a button with a Theme that calls FileSystemPicker will not work, because The FileSystemPicker is opened via Navigator.push. It takes the theme data from the application widget (MaterialApp/CupertinoApp). To customize the theme in FileSystemPicker, I need to inject custom theme support in FileSystemPicker. I will think about how it can be done, but it will not be implemented quickly.

**Comment by andyduke** [comment]
@jim012 Please try the [beta version 3.0](https://pub.dev/packages/filesystem_picker/versions/3.0.0-beta.1), will it solve your problem?

**Comment by jimschmit** [comment]
@andyduke it worked, thanks!
